[package]
name = "oxc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxc_allocator = "0.0.1"
oxc_ast = "0.0.3"
oxc_parser = "0.0.3"
